services:

  postgres:
    image: postgres
    container_name: postgr
    environment:
      POSTGRES_PASSWORD: 1234 
      POSTGRES_USER: db_user
      POSTGRES_DB: db
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data # after re-runnig DB-container we wont lose DB's data , and they will save in hard disk , bc inside of docker is connected to outside of docker 
        # informations inside the docker , will be saved outside of docker as well , so they wont be deleted 
  

  webapp:
    image: ai_web_app
    container_name: webapp
    networks:
      - mynetwork
    ports:
      - "8080:5000"
    volumes:
      - ".:/myapp"
    depends_on:
      - postgres  


  api_app:
    image: appapi
    container_name: apiapp
    networks:
      - mynetwork
    ports:
      - "8000:8000"  
    volumes:
      - ".:/app"



networks: 
  mynetwork :


volumes:
  postgres_data:




# docker run  --network mynetwork --name postgr -e POSTGRES_PASSWORD=pass -e POSTGRES_USER=username -e POSTGRES_DB=database -d postgres
# docker run -v .:/app -p 8080:5000 --network mynetwork webapp
# .:/app 
# . means current folder outside docker مسیر بیرون داکر و فایل های فعلی 
# /app means , current folder inside docker درون داکر فایل این مسیر رو تعریف کردیم به عنوان فولدری به نام اپ 